# Generated by Django 3.1.3 on 2020-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20191114_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catfact',
            name='fact',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
